### PR TITLE
fix cris-npp outage of 2021; add GEOS-IT support (zero-diff)

### PR DESCRIPTION
**Pull request by rtodling**
Fix for cris-npp shutoff/on 2021 case.

### CODE REVIEW

**Comment by rtodling** [comment]
This is zero-diff for cases before Oct 2021

**Review by tclune — APPROVED** [review]
cmake changes ok

**Comment by rtodling** [comment]
Thanks for checking Tom.

**Comment by gmao-msienkie** [comment]
I wouldn't say that this will "fix" the issue with CrIS-FSR NPP as your solution also will likely require a transfusion of bias coefficients.

**Review by jing-guo — APPROVED** [review]
For configuration file(s) for a specific system configuration, for example MERRA2 or in this case GEOSIT, I have always been wondering.  Would it be easier for maintenance by adding a branch than adding a subdirectory?  For example, we can have branches in parallel to develop, as parallel_develop/MERRA2_config, parallel_develop/GEOSIT_config, etc., where _config suggests that only a small collection of configuration files are (expected to be) different. 

Just a thought.

**Comment by rtodling** [comment]
Thanks Jing

**Comment by gmao-msienkie** [comment]
> For configuration file(s) for a specific system configuration, for example MERRA2 or in this case GEOSIT, I have always been wondering. Would it be easier for maintenance by adding a branch than adding a subdirectory? For example, we can have branches in parallel to develop, as parallel_develop/MERRA2_config, parallel_develop/GEOSIT_config, etc., where _config suggests that only a small collection of configuration files are (expected to be) different.
> 
> Just a thought.

In the case of MERRA2 the decision to use the regular DAS configuration or the MERRA2 configuration is done when the user runs 'fvsetup'.  It may be too much of an inconvenience to have the user need to check out a new branch and possibly rebuild if they wish to switch between running a historical run versus running near real time.  For the GEOSIT I think it is configured appropriately for a 3-D Var experiment and there may be some interest in being able to switch to that configuration via 'fvsetup' as well rather than having a separate build.

**Comment by jing-guo** [comment]
> In the case of MERRA2 the decision to use the regular DAS configuration or the MERRA2 configuration is done when the user runs 'fvsetup'. It may be too much of an inconvenience to have the user need to check out a new branch and possibly rebuild if they wish to switch between running a historical run versus running near real time. ...

Indeed, if _switching between configs after a build_ is a requirement, _creating another config object_ would be a reasonable solution for the problem.  I agree.

**Pull request merged**
