### PR TITLE
Feature/jguo/convinfo+pcscaling+icld det

### PR DESCRIPTION
**Pull request by jing-guo**
This branch is migrated from CVS GEOSadas revisions for issue #82.  The earlier implementation was made on top of a 5_27 release.  It is now rebase/merged to the most current develop branch (~5_29) with several minor corrections and some information added.
1. correct some convinfo.db/ files.
2. merge into an earlier pcscaling implementation with some informational changes.
3. implemented icld value configuration mechanism to make_satinfo.x, including CMakeLists.txt fixes.

### CODE REVIEW

**Review by tclune — APPROVED** [review]
CMake changes ok.

**Review by jing-guo — COMMENTED** [review]
For your (algorithm reviewers') convenience in "File changed" view, 
- Difference bars related to the algorithm of **icld** implementation are all in green.  They are _m_icld.F90_, _m_sirest.F90_, _main.F90_, and _sidb/icldtable.nml_.  
- Remaining files with green/red difference bars are mostly for updates/fixes/changes unrelated to the main algorithm of **icld** implementation, except for _CMakeLists.txt_ where new code files are added.

**Comment by rtodling** [comment]
Jing, thanks for this. 
Here is a question: why do you have changes in the active and available table files as compared to the what's in the develop branch?

**Comment by jing-guo** [comment]
> Here is a question: why do you have changes in the active and available table files as compared to the what's in the develop branch?

They are fixes to convinfo.db/ files, 
1. They are wrong in format, where count ```m``` in entries ```<otype>```-per-line does not match actual entry counts.  Often ```m``` were  supposed to be ```0```, and remained ```1``` after someone (Will?) had removed the ```<otype>``` . 
2. They apparently had never been used so far.  So I am not sure if that was the reason convinfo not been implemented.  So I fixed them anyway in case it would be used later.

**Comment by jing-guo** [comment]
Regarding the use of a ```namelist``` for the purpose.  It was very easy format to use in Fortran.   Now it was very powerful even for data input in a table form, where one may have found hard to do in Fortran 90 or earlier.

Similarly, ```namelist``` was also used in pcscaling.db/ for implementation.  The main idea is to avoid parsing data through hand coding.

**Comment by rtodling** [comment]
I am finding out that to run the new code I have to have a namelist available ... that is mksi.x now needs that namelist; all good, but that means the gsiinfo.pl script needs to be changed - I can do that.

But I still don't quite understand what the role of this namelist is wrt setting an active channel off - will we have to also change the namelist? 
Best to chat about this ...

**Comment by jing-guo** [comment]
> I am finding out that to run the new code I have to have a namelist available ... that is mksi.x now needs that namelist; all good, but that means the gsiinfo.pl script needs to be changed - I can do that.

I guess you can rename ```<>.nml``` to ```<>.tbl```, if you want.
> 
> But I still don't quite understand what the role of this namelist is wrt setting an active channel off - will we have to also change the namelist? Best to chat about this ...

- ```icldtable.nml``` defines ```icld``` values as a function of time.
- ```active.tbl``` and those ```iuse<>.tbl``` define ```iuse``` values as a function of time.

They refer to different variables, need to be specified separately.  Certainly ```icld``` would be meaningless if ```iuse``` were set to ```<= 0```.  So in the algorithm, ```mksi.x``` first rewrites ```iuse``` values from ```satinfo.tmpl``` according to ```active.tbl``` etc..  Then it rewrites ```icld``` values according to ```icldtable.nml```.

**Comment by jing-guo** [comment]
``mkis.x`` was a code designed and developed when ``iuse`` values were very simple, containing -1, 0, and 1 only.  So there were ``available.tbl`` and ``active.tbl`` two files, one _valid_ ``iuse`` value per file.  Then more ``iuse`` values were defined, including 2, 3, 4 etc.  One would wish we have had ``iuse`` values specified in ``active.tbl``, but it is too late now.   Managing and maintaining with many different ``iuse`` configuration values is becoming awkward.

In this ``icld`` case, we know ahead of time that multiple ``icld`` values are expected.  And I hope I have got the algorithm right this time.

**Comment by rtodling** [comment]
Well, I made a mistake in setting up the run - so that's why it crashed - I realize I don't need a change anywhere else to simply reproduce previous behavior, but I am still puzzled as to whether icld as you coded is doing what I had envisioned. Perhaps we can chat tomorrow morning ... would 9pm be ok?

**Comment by jing-guo** [comment]
Yes.  The key issue is indeed to confirm the algorithm against requirement.

**Comment by rtodling** [comment]
I tested these and can confirm the changes are zero diff.

**Review by rtodling — APPROVED** [review]
My test corroborates these to be zero diff.

**Comment by jing-guo** [comment]
One problem remains, will this implementation solve the original expectation of managing ``icld`` values for ``satinfo.txt`` file? 

If you need to have some changes, please let me know.

**Pull request merged**
