### PR TITLE
Updates for satinfo.db files - CrIS-FSR and MetOp-C IASI

### PR DESCRIPTION
**Pull request by gmao-msienkie**
Modified start times for instruments to match data in archive
Added gap in CrIS-FSR SNPP for mid-wave failure and switch to Side-2
Fixed stupid typos in my initial commits
Includes most recent SNPP outage after 5/21 18z

@will-mccarty @rtodling - I would appreciate your review of my changes.

### CODE REVIEW

**Comment by gmao-msienkie** [comment]
Technically the changes could be non-zero diff for the period when the Side-1 midwave channels failed and we switched to Side-2 electronics.  I added one day of passive data just as a precaution for any calibration mismatch.
For any tests with current dates the changes should be zero diff.

**Comment by gmao-msienkie** [comment]
@rtodling @will-mccarty  this PR includes the MetOp-C changes that I suggested along with other changes to correct the CrIS-FSR start dates.
Will add new tlapmean (or old tlapmean) for MetOp-C as recommended.

**Review by rtodling — APPROVED** [review]
These look ok by me.

**Comment by rtodling** [comment]
Actually, on second thought ... I don't understand what happened to the avhrr changes in tlapmean ...

**Comment by gmao-msienkie** [comment]
Oops, I may have conflicted with your change.  I saw the initial comment about avhrr, and copied the MetOp-B values from f5271_fp.   I had not seen those in any of the branches on GitHub.

**Comment by rtodling** [comment]
Meta, I mistakenly pointed you to develop instead of the branch I actually have 5_28 work being done ... not yet gone onto develop. You had to do extra work in this PR though some things were already in feature/rtodling/GEOSadas-5_28_0_m1 - my apologies. Since I brought you changes here onto the branch just mentioned I will close this PR - I will have my branch brought onto develop soon. Thank you again.

**Pull request closed without merging**
