### PR TITLE
updates for FSOI in NCDIAG

### PR DESCRIPTION
**Pull request by will-mccarty**
These updates are to enable the writing of the FSOI variables to the ncdiag format instead/in addition to within the binary files.  

The results were compared between the log file in the GSI log file and the NCDiag files, and they match exactly.

### CODE REVIEW

**Comment by gmao-msienkie** [comment]
There is a problem with genstats_gps.f90.  The code added to write out the FSOI variables to the nc4 file modifies the variable 'ioff', before it is written to the header of the binary diag file.  Thus the wrong value is written to the header which will cause trouble for the ODS conversion of the binary file.

**Comment by gmao-msienkie** [comment]
Also, the code in setupoz.f90 to write the FSOI variables for the layer ozone observations was left commented out.

**Comment by gmao-msienkie** [comment]
I pushed my branch 'feature/msienkie/NCDiag_Updates' which includes your changes as well as fixes for setupoz.f90 and genstats_gps.f90.  I also have a version of 'read_diags.f90' that changes the radiance variables in the nc4 section to r_single to match the current 'setuprad' output, and will skip reading the 'tpwc_amsua' variable if it is not available in the nc4 file.

**Comment by mathomp4** [comment]
@will-mccarty This probably will need to be redone with the new GEOSadas-5_27_1 candidate that is coming soon. Apologies

**Pull request closed without merging**
