### PR TITLE
Modify 'read_prepbufr' to provide time_launch for aircraft

### PR DESCRIPTION
**Pull request by gmao-msienkie**

### CODE REVIEW

**Comment by gmao-msienkie** [comment]
results should be zero diff except for modifying the nc4 diag to include 'launch time' for aircraft profiles.

**Review by gmao-jjin3 — APPROVED** [review]
Thanks!

**Review by rtodling — COMMENTED** [review]
Can somebody explain to me how is this zero-diff? Before it seems like the launch time was set to "undef"; now it's set to something meaningful ... this should impact the time interpolation (in the FGAT sense), shouldn't it? I understand this should not affect that cases when 

driftl=kx==120.or.kx==220.or.kx==221

is true,

but it will affect other cases ...

is this zero-diff because time_launch is only being used for diagnostic purposes?

**Comment by gmao-msienkie** [comment]
As far as I know 'time_launch' is only passed to the setupt and setupw routines to be written out the the nc4 files.  Thus I don't believe it has any affect on the assimilation.   In this case the additional code only sets time_launch for aircraft observations.  The other observation types (besides radiosonde) continue to have a missing value for 'time_launch' .  I believe we need 'time_launch' for use with Jedi so that the ascending/descending profiles for aircraft can be distinguished for the ObsErrorFactorConventional filter.  In the GSI this filter is applied separately for each ascending or descending profile (via errormod_aircraft) in a call from read_prepbufr, however the Jedi QC deals with all the observations at once and needs the information to distinguish the profiles.

**Comment by gmao-msienkie** [comment]
By the way, sorry about all the differences.  I have code set to strip out excess whitespace when I save files from 'vim'.

**Comment by rtodling** [comment]
Thanks Meta.

**Comment by rtodling** [comment]
Just to make sure - tested for zero diff ... good.

**Review by rtodling — APPROVED** [review]

**Pull request merged**
