### PR TITLE
Remove unused 'ifind' routine from setupt.f90

### PR DESCRIPTION
**Pull request by gmao-msienkie**
Somehow the 'ifind' routine keeps coming back - let's eliminate it once and for all.  It was used for MERRA2 aircraft BC but is not used for anything now.  I think I've asked to have it deleted more than once but maybe it is brought back with merges from NCEP or something.

### CODE REVIEW

**Comment by mathomp4** [comment]
@gmao-msienkie After discussion with @rtodling yesterday, I enable "required labels" on this repository. What this means that all PRs will now require a label between "0 diff", "0 diff structural", "0 diff trivial", and "non 0 diff". So, if you have a chance, can you add the appropriate label. Thanks :)

(Note: I toggled the bugfix label on and off to 'turn it on' since this PR was here before the check came in.)

**Comment by gmao-msienkie** [comment]
It -should- be zero diff but I will actually have to run a test to verify this.  I will apply the label after I have done this.
I'm just running a static analysis to verify I get the same results as my last 5_27 run.  Is there a process (yet) for verifying zero diff from 'develop' branch of the analyisis?

**Comment by gmao-msienkie** [comment]
Running the analysis with and without the routine produced zero diffs.

**Comment by rtodling** [comment]
This is being merge into feature/rtodling/GEOSadas-5_28_0

**Comment by rtodling** [comment]
Already on develop - rt-GEOSadas-5_28_0_p1

**Pull request closed without merging**
