### PR TITLE
R21C: Needed to handle OMPS-LP-N21

### PR DESCRIPTION
**Pull request by rtodling**
Ozinfo file was missing needed components to assimilate OMPS-LP from N21. I also changed the permissions in this file and another - no needed for these text files to be executables.

These are clearly only non-zero differences when data from N21 is available; otherwise, these are zero-diff.

**CHANGES AIMED AT R21C BRANCH**

### CODE REVIEW

**Review by kwargan — DISMISSED** [review]
Looks good to me

**Comment by kwargan** [comment]
N21 OMPS-LP also needs to be added to gmao_ozinfo.db (availabla.tbl and active.tbl). It will be identical to the N-SNN OMPS-LP except the start date. 

@kwargan Kris I have those fixes in my sandbox - not pushed yet since I am having problems running and using these input data files ... see below pls.

**Review by mathomp4 — DISMISSED** [review]

**Comment by rtodling** [comment]
> Looks good to me

@kwargan Actually: when I try using these in an x-exp like settings, the code crashes in error when trying to read either one of the files in the following obs-classes:

BEGIN r21c_npp_ompslp_nc => ompslpnc_npp.%y4%m2%d2.t%h2z.nc
 20130101_00z-21001231_18z 060000 /discover/nobackup/projects/gmao/input/dao_ops/ops/reanalysis/OMPS-LP/v2.6-adjusted-tint/Y%y4/M%m2/OMPS-LPoz-v2.6-adj.%y4%m2%d2_%h2z.nc
END 
BEGIN m2scr_n21_ompslp_nc => ompslpnc_n21.%y4%m2%d2.t%h2z.nc
 20230301_00z-21001231_18z 060000 /discover/nobackup/projects/gmao/m2scream/data/ompslp-n21/adjusted/Y%y4/M%m2/OMPS-LPoz-n21-v1.0.%y4%m2%d2_%h2z.nc
END

For the x-exp I put both N21 and NPP  together in the same experiment - the code seems to think the number of levels is 61+61=122 ... I can't put my finger one what could be wrong. I haven't tried in the R21C settings, but I checked the codes for ozone handling and they are the same between the R21C and what I am using for x-exp!

**Comment by rtodling** [comment]
@kwargan can you point me to the scream experiment? I assume that experiment is using both sources of OMPS-LP?!

**Comment by rtodling** [comment]
@kwargan I think I found a bug in the reading of the nc ozone files ...

**Comment by rtodling** [comment]
@kwargan I now added to this what I believe is a fix for the issue I had in trying to get more than one source of OMPS-LP processed in the code - just by augmenting the ozinfo table was enough for the code to be unhappy - even when a single source is passed gsi.rc ... the change in the Fortran code here fixes the issue. I am putting this here for M21C and also adding the same change in another PR for 5.41.x

**Comment by rtodling** [comment]
@kwargan or @elakkraoui Can one of you approve this? This is good by me and I'd like to close on this.

**Review by elakkraoui — APPROVED** [review]

**Review by mathomp4 — APPROVED** [review]

**Comment by rtodling** [comment]
Hi @mathomp4 , can you please approve this when you have a chance? This has been revised and it's also a part of what I have incorporated in the 5.41.x version of GEOSadas. Thanks.

**Pull request merged**
