### PR TITLE
Skip "Forecast_adjusted" in radiance ncdiag files

### PR DESCRIPTION
**Pull request by gmao-jjin3**
The variable "Forecast_adjusted" is removed from NC_diag files in order to avoid confusion and error in IODA converter, because it is not correct for some radiance data such CRIS-FSR.  It should be "sngl(tb_obs(ich_diag(i))-tbc**0**(ich_diag(i)))".  Corrected "Forecast_adjusted" can be derived from the two variabless "Observation" and "Obs_Minus_Forecast_adjusted".

### CODE REVIEW

**Comment by gmao-yzhu** [comment]
This code change looks fine to me.

From: Jianjun Jin ***@***.***>
Reply-To: GEOS-ESM/GEOSana_GridComp ***@***.***>
Date: Sunday, June 25, 2023 at 10:48 PM
To: GEOS-ESM/GEOSana_GridComp ***@***.***>
Cc: "Zhu, Yanqiu (GSFC-6101)" ***@***.***>, Review requested ***@***.***>
Subject: [EXTERNAL] [BULK] Re: [GEOS-ESM/GEOSana_GridComp] Skip "Forecast_adjusted" in radiance ncdiag files (PR #136)

CAUTION: This email originated from outside of NASA.  Please take care when clicking links or opening attachments.  Use the "Report Message" button to report suspicious messages to the NASA SOC.



@gmao-jjin3<https://github.com/gmao-jjin3> requested your review on: #136<https://github.com/GEOS-ESM/GEOSana_GridComp/pull/136> Skip "Forecast_adjusted" in radiance ncdiag files.

**Review by gmao-yzhu — APPROVED** [review]
The code change looks fine to me.

**Review by gmao-wgu — APPROVED** [review]

**Review by rtodling — COMMENTED** [review]
Does it really hurt to keep this in the diag file?

**Comment by gmao-jjin3** [comment]
> Does it really hurt to keep this in the diag file?

No, it doesn't.  We are able to get around it in IODA converter now.

**Review by rtodling — APPROVED** [review]
Not backward compatible ... but I guess nobody cares about this in the nc4 diag files!

**Pull request merged**
