### PR TITLE
Turn off CrIS-SNPP after 18z 20230813 when side 2 long-wave fails

### PR DESCRIPTION
**Pull request by gmao-msienkie**
SNPP CrIS went away on 8/14 after failure.
SNPP CrIS returns 9/7 when it comes back without LW, no longer useful for our purposes

### CODE REVIEW

**Comment by gmao-msienkie** [comment]
Zero diff prior to 9/7 when the CrIS SNPP data comes back without the LW channels.  
I never know whether to call these things zero-diff or not...

I looked in the archive and the data was mostly missing 8/14 00z up to the end of the month so I set the turn-off 18z 20230813 though this does not match the configuration in FP.
I also modified the R21C and GEOS-IT active_channels.tbl.

**Comment by rtodling** [comment]
That's too bad - it looks like x0046d (as FP) assimilated these data!

**Review by rtodling — APPROVED** [review]
It seems fine w/ me - will need to retro-feed this to GEOS-IT; again, x0046d seems to have used these bad data.

**Comment by gmao-msienkie** [comment]
After CrIS-FSR NPP had been gone for so long I didn't expect it to come back so I hadn't been checking.
The issue of CrIS-FSR NPP going out came up in today's reanalysis meeting and when I saw it was there again since the 7th of September I thought holy cow, I'd better make sure this information gets into future tags.  Of the data coming in we would only have 7 mid-wave channels that we assimilate which is too few to use.

**Pull request merged**
