### PR TITLE
Add end dates for MetOp-A AMSU-A AVHRR ASCAT 

### PR DESCRIPTION
**Pull request by gmao-msienkie**
Implement changes for #66 - prepare for MetOp-A decommissioning
in mksi/sidb
* turn off MetOp-A AMSU-A and AVHRR in active_channels.tbl
* add end date for MetOp-A AMSU-A AVHRR HIRS MHS in available_channels.tbl
* turn off ch 14 iuse=4 in iuseClass-4_channels.tbl
* turn on MetOp-B and NOAA 19 AVHRR

turn off MetOp-A ASCAT (kx=290, satid 4) in gmao_global_convinfo.txt 

Using 20210918/12z as transition date (as tested in f5721_metop)

### CODE REVIEW

**Comment by gmao-msienkie** [comment]
non-zero diff even prior to transition date because MetOp-A AVHRR is replaced with MetOp-B AVHRR

**Comment by jing-guo** [comment]
> non-zero diff even prior to transition date because MetOp-A AVHRR is replaced with MetOp-B AVHRR

Shouldn't this be considered as **_observation-configuration_**?

**Comment by gmao-msienkie** [comment]
Oh, I mistyped that  - I have to watch it with these late night edits.  What I meant to say is that MetOp-A **ASCAT** is removed and replaced with MetOp-B **ASCAT** (not AVHRR).  Since we do not have a time dependent convinfo configured yet - the switch to MetOpB ASCAT affects all dates, so it is non-zero-diff.
The "observation-configuration" was a label I added because I have been doing a lot of edits of the observation database where for dates prior to an observation change the assimilation was zero-diff and after the change the assimilation would not be zero-diff.  And, because these have been changes for recent events assimilation tests like the X-experiments would not yet be affected because they are still before the effective dates.  Except, of course, for this case as I noted above.
Per Matt's note there are specific labels for the label check and 'observation configuration' is not one of the required ones.

**Comment by rtodling** [comment]
Meta, I just updated the branch, but it seems from the email of last night (and I quote):

**So I had a look today at the FP plots, since I wanted to see how the stats and bias correction evolved since the 23 September 12z incident.** 

**What I am thinking is that we can window out the data at 12z Sep 23 – possibly in the obsys-nccs.rc or alternatively in the active_channels.tbl/available_channels.tbl (since we don’t want the bad data affecting channels while they are passive.** 

that you propose to move the date of turning off. So, can you update this branch accordingly so I can get it to fold onto develop? 
Thanks

**Comment by gmao-msienkie** [comment]
Ricardo, the email you referenced is for a separate issue with the AIRS instrument that occurred shortly after the f5271_metop test began.  When approved, whichever changes we decide to make will go in as a separate PR.
There will also need to be an additional PR for the change to turn on the CrIS-FSR NPP instrument but that issue also needs further investigation.

This PR covers only the changes for the other instruments (turn off MetOp-A, turn on AVHRR for N19 and MetOp-B, turn on MetOp-B ASCAT).  While issue #66 mentions other possible dates for the switch I think the ones in this branch are what we are going with.

**Comment by rtodling** [comment]
Got it!

**Review by rtodling — APPROVED** [review]
These seem fine to me.

**Pull request merged**
