### PR TITLE
Extract mksi into new repo

### LINKED ISSUE #289: Split GSI's mksi into its own repo
To facilitate the transition to JEDI, it would be good to have mksi sit its own repo - but be placed in the same GSI_GridComp location as it stands when GEOSadas is built. 

Added Akira here so she can update swell once the change has been made.

### PR DESCRIPTION
**Pull request by mathomp4**
This PR along with https://github.com/GEOS-ESM/GEOSadas/pull/267 is an attempt to extract the `mksi` folder in GEOSana_GridComp into its own repo. To do so, the [RepoExtractor tool](https://github.com/GMAO-SI-Team/RepoExtractor/tree/main) was run as:
```
./extract_repo.bash -r "GEOSana_GridComp" -d "mksi" --newrepo "GEOS_mksi" --develop --create-repo --push
```
and a new repo GEOS_mksi was created:

https://github.com/GEOS-ESM/GEOS_mksi

Then GEOS_mksi was added as a new component and placed as `@mksi/` under `GSI_GridComp/`

Tests show it *builds* which should be proof it is correct, but probably needs testing to be sure. 

And of course, before anything is done, tags should be made in GEOS_mksi and GEOSana_GridComp.

Closes https://github.com/GEOS-ESM/swell/issues/289

### CODE REVIEW

**Review by rtodling — APPROVED** [review]

**Review by rtodling — DISMISSED** [review]

**Comment by rtodling** [comment]
@mathomp4 Have Matt, can we just get this in?

**Comment by mathomp4** [comment]
> @mathomp4 Have Matt, can we just get this in?

Oh sure. Let me fix the conflicts and then you can merge.

**Review by pchakraborty — APPROVED** [review]

**Comment by mathomp4** [comment]
@rtodling I fixed up the conflicts and it should be good to go. You can re-approve and merge as you wish.

**Review by rtodling — APPROVED** [review]
Thank you.

**Pull request merged**
