### PR TITLE
Turn off IASI MetOp-C 27-29 July 2021 due to observation problem

### PR DESCRIPTION
**Pull request by gmao-msienkie**
Modified active_channels.tbl to turn off MetOp-C IASI between 27-29 July due to problems with the observations, per and email forwarded from Will.  @will-mccarty 

----------
From: Chris Burrows <Chris.Burrows@ecmwf.int> 
Sent: Friday, July 30, 2021 2:32 PM
To: herve.benichou <herve.benichou@meteo.fr>; Harlow, Chawn <chawn.harlow@metoffice.gov.uk>; itwg nwp <itwg_nwp@lists.wisc.edu>
Subject: Re: IASI-C issues after maintenance

Hi All,
 
I contacted EUMETSAT about this, and received this response:
 
"""
The problem indeed originates from the maintenance that was planned on Tuesday 27th, that was a power cycle: we have  noticed after this that the baselines of the interferograms were not converging towards the initial and expected values. After a short investigation, it was discovered that the operational settings of the MAS subsystem (offsets and gains) was not uploaded. Adjustment to the operational settings used before the power cycle was performed on Thursday the 29th and IASI-C was back in NORMOP at around 2021-07-29 11:11 UTC.
"""
 
Chris

### CODE REVIEW

**Comment by gmao-msienkie** [comment]
I'm not sure how to label this - is it a 'bug' to have bad observations going in, or should it be classified as something else.  In any case the data is not yet being used operationally but we anticipate it going in the next release.

**Comment by mathomp4** [comment]
@gmao-msienkie You might have discovered a need for more and different labels here in GEOSana_GridComp. If you or @rtodling think of any you'd like, let me know and I can add them (actually, I think anyone can).

So "bad satellite obs" or whatever to help people figure out things :)

**Comment by gmao-msienkie** [comment]
I thought I would be bold and add the label 'observation configuration' - of course since apparently anyone can edit the labels it can be modified if desired.   We could use that label for modifying other tables like convinfo and the obsys.rc as data streams come and go.

**Review by rtodling — APPROVED** [review]
I suppose this is all good - you know better.

**Pull request merged**
