### PR TITLE
Save GSI diagnosed pressure for wind data.

### PR DESCRIPTION
**Pull request by gmao-jjin3**
Save original GSI diagnosed pressure for wind data.

### CODE REVIEW

**Comment by gmao-jjin3** [comment]
@rtodling  Let's save the original GSI diagnosed pressure (presw) as "Pressure_GSI".

**Comment by danholdaway** [comment]
Do we need it for something? Is it just for checking? We don't want to cause a confusion that this is needed in the UFO YAMLs

**Comment by gmao-jjin3** [comment]
@danholdaway  No, we don't need it for UFO. Actually, we don't want it in UFO. It is not in the IODA converter either. Just in case we want to check it later.

**Review by danholdaway — APPROVED** [review]

**Review by rtodling — COMMENTED** [review]
JJ: has is different from what you just placed in a PR from a couple of days ago? What that PR not correct?

**Comment by gmao-jjin3** [comment]
@rtodling  That one replaced the "Pressure" values, and this one saves "presw*1000" to  "diagnosed_Pressure".

Here is difference from x0048 in setupw.f90 
```
1767c1767,1768
<            call nc_diag_metadata("Pressure",                sngl(presw*r100)       )
---
>            call nc_diag_metadata("diagnosed_Pressure",      sngl(presw*r100)       )
>            call nc_diag_metadata("Pressure",                sngl(r1000*exp(data(ipres,i))))

```

**Comment by rtodling** [comment]
> @rtodling That one replaced the "Pressure" values, and this one saves "presw*1000" to "diagnosed_Pressure".
> 
> Here is difference from x0048 in setupw.f90
> 
> ```
> 1767c1767,1768
> <            call nc_diag_metadata("Pressure",                sngl(presw*r100)       )
> ---
> >            call nc_diag_metadata("diagnosed_Pressure",      sngl(presw*r100)       )
> >            call nc_diag_metadata("Pressure",                sngl(r1000*exp(data(ipres,i))))
> ```

I don't have too much of a problem w/ this with the exception that it's starting to be difficult to tell what is true GEOVALS vs what is not. There is an effort to enable the GEOS model to produce the GEOVALS for various instruments in GSI. Part of that exercise is to look at the GEOVALS in the diag files and make proper adjustments to GEOS so it can write out the geovals ... the more "diagnostic" stuff like this is written out, the harder it is to tell what's needed and what just there for diagnostic purposes ... I will say though that at least this one is named diagnosed_something which might ease the pain ... I will take it in as is.

thanks/

**Review by rtodling — APPROVED** [review]
This is not ideal, but it is fine.

**Pull request merged**
