### PR TITLE
sat-wind (GOES-R) reconfig; supportf for L181 and L91

### PR DESCRIPTION
**Pull request by rtodling**
This provides support of L91 and L181 and incorporates GOES-R reconfiguration.

### CODE REVIEW

**Comment by mathomp4** [comment]
@rtodling Is this needed for a 5.29.0 release?

**Review by tclune — DISMISSED** [review]
cmake changes are fine

**Comment by rtodling** [comment]
It had a label!

**Review by tclune — COMMENTED** [review]
cmake changes ok

**Review by mathomp4 — APPROVED** [review]
I guess I'll approve. Far be it from me to assume I know more about GSI et al than @rtodling ! 😄

**Comment by rtodling** [comment]
Thank you Matt - I appreciate all the work.

**Pull request merged**
