### PR TITLE
Feature/rtodling/geo sadas 5 29 0

### PR DESCRIPTION
**Pull request by rtodling**
This is now the code that works w/ MAPL-2. This is what I plan to call 5.29; so if we are putting version numbers on this I suggest v5.29.0 - will be suggesting the same of other codes going in from different repos so they all have consistent names. 

This is about to be tagged rt-GEOSadas-5_29_0_prep2

### CODE REVIEW

**Comment by mathomp4** [comment]
Adding Ben as a reviewer as he can look at transition code better than I can

**Comment by gmao-msienkie** [comment]
I just noticed that I hadn't put the entries for iasi_metop-c in the gsi.rc.tmpl and associated files.  Fixed in my branch.
#       modified:   gsi.rc.tmpl
#       modified:   gsi_fdda_1.rc.tmpl
#       modified:   gsi_fdda_2.rc.tmpl
#       modified:   gsi_fgat_1.rc.tmpl
#       modified:   gsi_fgat_2.rc.tmpl
#       modified:   gsi_sens.rc.tmpl

**Review by mathomp4 — APPROVED** [review]
If @rtodling is happy with this, I am happy with this.

**Comment by mathomp4** [comment]
> I just noticed that I hadn't put the entries for iasi_metop-c in the gsi.rc.tmpl and associated files. Fixed in my branch.
> modified: gsi.rc.tmpl
> modified: gsi_fdda_1.rc.tmpl
> modified: gsi_fdda_2.rc.tmpl
> modified: gsi_fgat_1.rc.tmpl
> modified: gsi_fgat_2.rc.tmpl
> modified: gsi_sens.rc.tmpl
> 
> these changes will also need to be made in this branch.

@gmao-msienkie I'd like to make a release of what's in this branch. Can you make these changes here?

**Comment by mathomp4** [comment]
Actually, @gmao-msienkie I'll pull this into `develop` now. I'll then work with you on the other files. We know @rtodling is happy with this.

**Pull request merged**
