### PR TITLE
Skip identical conventional observations.

### PR DESCRIPTION
**Pull request by gmao-jjin3**
A few minor changes in order to make inflated observational errors of conventional observations identical to those values in GEOS. 
 (1) Keep only one of those conventional observations which are made at the same locations, level, and time, and discard the rest of them. As a result, we can avoid losing those data in IODA converter, and have same duplicate factors in JEDI as in GSI.
(2) Determine duplicate factors by single precision geo-location values since single precision values are saved in NC_Diag files and then used in JEDI/UFO.
(3) Not to consider sensible temperature and virtual temperature made at same locations as duplicated observations.
(4) Save observation types (kx) of duplicated observations in NC_Diag files.

### CODE REVIEW

**Comment by gmao-jjin3** [comment]
@rtodling  I saw your email yesterday and I tend to withdraw these changes.  They are merely for UFO configuration. I don't know exactly how significant their impact in GSI.  We probably don't want add these changes in GSI if the impact is significant.  If the impact is insignificant, on the other hand, those differences in inflated errors between GSI and UFO should have insignificant impact in JEDI results too.  @danholdaway how do you think?

**Comment by rtodling** [comment]
I commented the prints in the setup's here related to the duplicate obs ... too many of them.

**Review by rtodling — APPROVED** [review]
This looks reasonable to me. I did a little test; I see some obs get tossed, but only very few - looks good. Thanks.

**Comment by gmao-jjin3** [comment]
> I commented the prints in the setup's here related to the duplicate obs ... too many of them.

No problem at all.

**Pull request merged**
