### PR TITLE
Modify marine PS fix - check PMO quality before substituting for POB

### PR DESCRIPTION
**Pull request by gmao-msienkie**
When I was working on modifying some JEDI code to convert prepbufr to IODA I noticed the prepbufr files have a flag PMIN which indicates whether the mean sea level pressure (PMO) was from the marine observation or if it was a derived value.
The data we use from the GDAS does not have any derived/calculated sea level pressures - the DOPMSL flag is false in the prepbufr processing.  However I think we would only want the observed pressures used for the substitution.
While I was thinking about checking the PMIN value I also realized that I was not checking the quality flag for PMO (i.e. PMQ) to see if the PMO observation was considered good.  I scanned through a few months of gdas.prepbufr files and saw that all of the cases where the PMQ mark was bad (PMQ=15) were also cases where PQM also indicated a bad pressure observation.  That means we have not been harmed (yet) by skipping this check.
For the sake of completeness I have added code to check PMQ and PMIN and will not change the pressure value if the mean sea level pressure is bad or is derived rather than measured.  I am currently running some tests to see the impact of the change on the assimilation.   I think it would not be completly zero-diff since we'll skip modifying POB when PMO is bad.  However since these will be bad POB obs that are not used in the assimilation it should not change the analysis results.

### CODE REVIEW

**Comment by gmao-msienkie** [comment]
I'm not sure if I should maybe label this zero diff.  I ran a pair of static analysis jobs, one with the x0049 GSIsa.x and one with a GSIsa.x with the modifications in this tag.  When comparing the anasa_stats.log files there were six more kx=180 obs that were rejected (presumably not corrected in the new tag because of the PMQ) and six less kx=180 obs monitored and corresponding changes in the stats for kx=180 mon and rej. Presumably these are the same obs that had bad quality marks coming in and were rejected by the gross check because they had not been corrected as in x0049.  Everything else in the stats log was identical to all decimal places so I don't think I need to compare analysis fields or obs.  Zeroish diff?

**Comment by gmao-msienkie** [comment]
@rtodling hopefully this can go in to a new tag soon (x0050?)
As far as I can tell the extra checking did not make a difference in the results but I think we still should screen the obs in case our input stream changed to include derived values for MSLP.

**Comment by gmao-msienkie** [comment]
@rtodling still hoping to get these changes in the next tag whatever it is.

**Review by rtodling — APPROVED** [review]
Thank you Meta.

**Pull request merged**
