### PR TITLE
Changes made in GSI to assimilate all-sky ATMS

### PR DESCRIPTION
**Pull request by mjkagnes123**
Changes to assimilate all-sky ATMS water vapor channels. The changes were made on top of x0045a.

### CODE REVIEW

**Comment by jing-guo** [comment]
GitHub is asking to "merge the latest changes from develop into this branch".  Although I tried it without any problem, it seems gitHub is expecting it to be done from you.  

Also, it might be helpful for information tracking if you can include some very brief descriptions for each intended subjects included in this change set, as while as justifications of inclusion in the coming release.

**Review by jing-guo — APPROVED** [review]
I merged and approved this changeset toward the current develop HEAD.

**Comment by gmao-msienkie** [comment]
There is a requirement to add a label (see on upper right hand side of the page) to a PR for it to be accepted.  Judging from the content I added 'enhancement' - this can be changed if it is not appropriate.

**Review by jing-guo — APPROVED** [review]

**Comment by jing-guo** [comment]
Thanks Meta for fixing the status label!  

For now, I am still not able to get over with "all checks have failed" flag.

I am sending the issue to Matt for advice.

**Comment by mathomp4** [comment]
> Thanks Meta for fixing the status label!
> 
> For now, I am still not able to get over with "all checks have failed" flag.
> 
> I am sending the issue to Matt for advice.

@jing-guo The issue is that the "required" labels are:

* 0-diff
* 0-diff trivial
* 0-diff structural
* non-0-diff

We require one of those so that gatekeepers know if a PR should change the "answer" of the model/code or not. So, I suppose this is non-zero-diff? Not sure how to label it.

**Comment by jing-guo** [comment]
After updated to the current develop HEAD, this change contains only a feature enhancement to proper processing of ATMS observation.  And it should be zero-diff, if ATMS is not in use.  Based on this, I do want to set the required label to **_zero-diff_** with **_enhancement_**.

However, this change (after synched to the current develop HEAD) does contain differences in their ATMS channel info configuration data.  With this consideration, it is also labeled with **_observation-configuration_**, to catch integrators' attention.

**Comment by rtodling** [comment]
Jing - as it turned out this code was not at all zero-diff. The fact that this was put on develop messed me up big time.  Please next time let's review only the ticket in question. Thanks.

**Pull request merged**
