### PR TITLE
Feature/wrmccart/commercial ro

### PR DESCRIPTION
**Pull request by will-mccarty**
Code changes (mostly KX tracing, new QC excluding data below 8 km for GLONASS & 5 km for GPS) for GeoOptics (kx = 265).  Also includes Spire (kx == 269) updates (again, mostly kx tracing, new QC excluding data below 8 km for GLONASS & 5 km for GPS).  

This pull request also includes turning on KOMPSAT-5 (kx == 825) & PAZ (44) in the convinfo in addition to the commercial data

These QC choices are not wrapped in a gsi.rc-controllable logical, but in the future, these will have to potentially be rectified w/ a slew of code changes from NCEP.  Thus, at that point, we may need to isolate QC procedures.  For now, this is reasonable IMO.

### CODE REVIEW

**Comment by will-mccarty** [comment]
Note - zero diff unless running w/ commercial data (both Spire & GeoOptics will not be zero-diff).  Spire is not zero-diff because this configuration is designed for the NOAA CDAAC-processed data.  Future efforts will have to delineate between NOAA/COSMIC-processed data and Spire-Processed data

**Comment by will-mccarty** [comment]
Updated

**Comment by rtodling** [comment]
This is being merge into branch: feature/rtodling/rt-GEOSadas-5_28_0

**Review by rtodling — APPROVED** [review]
fine by me

**Pull request merged**
