### PR TITLE
Feature/rtodling/nc diag rev1

### PR DESCRIPTION
**Pull request by rtodling**
The following have been changed as minor updates to nc-diag generation:

      modified:   analyzer             - protect use of external sfc file; prep for handling pe files as directories 
       modified:   etc/gsi.rc.tmpl      - define plat for profl; prep for pe-files handling as dirs
       modified:   etc/gsi_fdda_1.rc.tmpl - prep for pe-files handling as dirs
       modified:   etc/gsi_fdda_2.rc.tmpl - prep for pe-files handling as dirs
       modified:   etc/gsi_fgat_1.rc.tmpl - prep for pe-files handling as dirs
       modified:   etc/gsi_fgat_2.rc.tmpl - prep for pe-files handling as dirs
       modified:   etc/gsi_sens.rc.tmpl - prep for pe-files handling as dirs
       modified:   etc/gsidiags.rc - prep for pe-files handling as dirs
       modified:   etc/obs.rc.tmpl - prep for pe-files handling as dirs
       modified:   gsidiags - prep for pe-files handling as dirs
       deleted:    nc_diag_read_mod.f90   - this does not belog here 
       deleted:    nc_diag_write_mod.f90  - this does not belog here
       modified:   setupdw.f90  - no nc4 file for pe w/o data (nobs=0)
       modified:   setupps.f90  - no nc4 file for pe w/o data (nobs=0)
       modified:   setuppw.f90  - no nc4 file for pe w/o data (nobs=0)
       modified:   setupq.f90   - no nc4 file for pe w/o data (nobs=0)
       modified:   setuprad.f90 - equalized bin/nc4 output within reason
       modified:   setuprw.f90  - no nc4 file for pe w/o data (nobs=0)
       modified:   setupspd.f90 - no nc4 file for pe w/o data (nobs=0)
       modified:   setupt.f90  - no nc4 file for pe w/o data (nobs=0); split file w/ defined dplat
       modified:   setupw.f90  - no nc4 file for pe w/o data (nobs=0); split file w/ defined dplat

Other changes in this branch are minor:

- add handle to tap on berror covariance
- add handle to have diag flies written in directories (as done at NCEP) - still to check if pays off.
- optional output of external sfc fields
- memory management in hybrid component

### CODE REVIEW

**Comment by rtodling** [comment]
Sorry - not sure what happened to the font!  I tried adding comments to the change and I got the garbage!! Sorry - in any case, the changes are ok.

**Comment by mathomp4** [comment]
> Sorry - not sure what happened to the font! I tried adding comments to the change and I got the garbage!! Sorry - in any case, the changes are ok.

Ah. You have a "#" character. If that's at the start of a line in Markdown, you get a Class 1 Heading. Big Font!

You can change it to a "-" or "*" to get a list (like you have at the end). Or you could surround it with triple-backticks to get a code block

**Review by mathomp4 — DISMISSED** [review]
I'll approve for CMake which will also approve overall. As usual, trust Ricardo with GSI!

**Comment by rtodling** [comment]
Thanks Matt - I will be observant of "#" characters in the future.

**Comment by rtodling** [comment]
I am closing this ticket as the ultimate changes to the NC4 files stuff are in upcoming update.

**Comment by rtodling** [comment]
Actually all changes are here.

**Review by jing-guo — DISMISSED** [review]
Changes reviewed.  They are acceptable.

Other concerns:
1. Changes to some diag_conv_file names with dplat flags.  Should this change apply to  all diag_conv observation streams?
2. Two dead statementss referencing to variable varinv0 have been removed.

**Comment by jing-guo** [comment]
After its conflicts with develop HEAD in active_channels.tbl by taking what are already in the develop HEAD, and with a green check "All checks have passed".  It still shows "merging is blocked".

**Review by jing-guo — APPROVED** [review]
Hope this time it works!

**Comment by jing-guo** [comment]
I add Meta for the next "1 approving review", if that is why the merge is blocked.
1. sometime we don't want automatic merging to take place, then it does.
2. sometime we do want automatic merging to take place, then it won't.
Not have a clude.

**Comment by jing-guo** [comment]
Not have a clue. :-)

**Comment by rtodling** [comment]
We don't do auto-merge/update Jing.
I don't think Meta is a person w/ approval powers in the case here - perhaps she should be at some point.

**Comment by jing-guo** [comment]
> We don't do auto-merge/update Jing. I don't think Meta is a person w/ approval powers in the case here - perhaps she should be at some point.

But this page is showing the old reason "merging can be performed automatically with 1 ..." for why "Merging is blocked", while I do have some approval powers.

So taking your advice, I removed Meta for this purpose, and assign you as the next assignee, with the understanding that "_the one made change, can not approve the change_", since I did make some minor but additional changes to resolve conflicts.

Regarding "auto-merge", I still feel there are something in the process that I don't have a full control over the outcome.  I will keep observing.

**Comment by rtodling** [comment]
The branch is now in sync w/ Meta's changes ... Jing can you approve it please?

**Review by jing-guo — APPROVED** [review]
Approved.

**Comment by jing-guo** [comment]
There must be some step missing in this PR process.  My later code-review or approval won't make a difference.

May be we should send to Matt for advice.

**Review by mathomp4 — APPROVED** [review]

**Pull request merged**
