### PR TITLE
Feature/msienkie/gsi1633 satwnd changes

### PR DESCRIPTION
**Pull request by gmao-msienkie**
The code for assimilating new AMV types has been copied from NCEP's gsi v16.3.3.  The 'read_satwnd.f90' has been modified to recognize the new BUFR subset NC005081 for EUMETSAT AVHRR winds from MetOp-B and -C.  An error in the specification of satellite IDs for VIIRS winds is corrected.  Code has also been added to process the LEO-GEO winds (subset NC005072, kx=255) and to read an upcoming version of JMA winds (subsets NC005047, NC005048 and NC005049).  
The convinfo file and database has also been modified to add MetOp-C AVHRR winds, LEO-GEO winds and VIIRS winds from NOAA-21 - all as passive.
The code for processing the new EUMETSAT MetOp AVHRR winds and the code fix for the VIIRS wind have been tested by carrying out several static analyses and checking the output obs and anasa_stats.

The code for new JMA winds has not been tested, it is not available in the operational stream.  (That code could be backed out of the update if so desired.)

### CODE REVIEW

**Comment by gmao-msienkie** [comment]
impact of changes:  (a) will now read in the new MetOp-B and C AVHRR winds and assimilate MetOp-B AVHRR winds
(b) VIIRS winds now read in and screen data based on the QI checks.  (Previously this part of the code had been skipped due to the bad specification of satellite IDs.)
(c) LEO-GEO winds are read in as passive
(d) New JMA wind subsets will be able to be read in

**Comment by gmao-msienkie** [comment]
I just added an entry to the convinfo active.tbl to turn on GOES-18 AMVs when they become operational on 4 January 2023

**Comment by gmao-msienkie** [comment]
Is there a plan to get these changes in FPP or will it have to wait for the next system?

**Comment by gmao-msienkie** [comment]
Is there a plan to get these changes in FPP or will it have to wait for the next system?

**Comment by gmao-msienkie** [comment]
FYI, the data subset for the new AVHRR wind (NC005081) starts in our satwnd bufr files on 20221130/12z - so any analysis before that date should be zero diff.  
The prior version of AVHRR data for MetOp-B (satid=3) drops out of the satwnd bufr file subset NC005080 on 20221103/00z and after that we do not have the prior format AVHRR wind for MetOp-B.

**Comment by gmao-msienkie** [comment]
I noticed in the prior comment that I had added MetOp-C AVHRR to the convinfo database as passive.  I guess after we have tested and approved the data we would also want to modify the database to turn on MetOp-C AVHRR (subtype 5) after 221130/12z.

**Comment by gmao-msienkie** [comment]
If we just wanted to bring in the code and keep things zero-diff until after the AVHRR data had been tested we would just need turn off AVHRR winds for MetOp-B (and C) at 221130/12z.  The VIIRS and LEO-GEO winds are not turned on so there should not be a difference in the analysis.  The new JMA types (NC005047, NC005048, NC005049) have not been added to our input satwnd bufr files yet.

**Review by rtodling — APPROVED** [review]
This looks good to me. I will add this to what will be 5.30.2. The tag will initially serve to run over the 2021-22 winter case; which is find from the perspective of the changes here since they should not interfere or introduce anything new over that period; and will aid the system to use the changes introduced here when placed in FP.

**Pull request merged**
