### PR TITLE
Update various reanalysis-related resource files for GEOSIT and R21C

### PR DESCRIPTION
**Pull request by elakkraoui**

### CODE REVIEW

**Review by rtodling — COMMENTED** [review]
Amal, 
We talked this: we don't want to add gmao_global_convinfo.ASCAT... can you please remove this?

**Comment by elakkraoui** [comment]
> 

Done.

**Review by rtodling — COMMENTED** [review]
Amal - thanks for removing the files. It hit me that w/ the conv-info database in place, you also don't need a convinfo file in GEOSIT or R21C ... the standard conv-info is a general template - what is in develop already includes the extra data types you added - no harm to FP like system. Can you pls also remove the convinfo from GEOSIT; you can save it for yourself so you can verify that what I say is correct, ie, you get the convinfo you want for the right period when using the db.

**Comment by elakkraoui** [comment]
> Amal - thanks for removing the files. It hit me that w/ the conv-info database in place, you also don't need a convinfo file in GEOSIT or R21C ... the standard conv-info is a general template - what is in develop already includes the extra data types you added - no harm to FP like system. Can you pls also remove the convinfo from GEOSIT; you can save it for yourself so you can verify that what I say is correct, ie, you get the convinfo you want for the right period when using the db.

Got it! I removed the other two as well.

**Review by rtodling — APPROVED** [review]
These seem fine w/ me.

**Pull request merged**
