### PR TITLE
Feature/jstassi/#98 convert scripts to python3

### PR DESCRIPTION
**Pull request by gmao-jstassi**

### CODE REVIEW

**Comment by gmao-jstassi** [comment]
Ricardo, these updates are utility programs that do not have any impact on DAS processing.

**Review by rtodling — CHANGES_REQUESTED** [review]
Joe,

I might have been distract when this come into the develop - I don't actually recall ever approving this stuff ... but that's besides the point. 

I can't approve this as is. This needs major cleaning. 

Why are there copies of RC files from ETC in the input directory of the python utils you added - I know this has been the case for a while, but I don't recall approving this. Regardless, it cannot be as is

- What is there an outdir w/ a single README file ... this seem like something that should be created when user run you software somewhere else outside the source code ... this dir should not be here.

- what are all these files? Why are some of these files copy of each other?  e.g.:  check_summary.satbang_full_rst check_summary.satbang_full_rst.orig are identical. Are these files output of a run using your software ... why should they be in the repo at all.

Sorry, but I think this needs some attention before it can be taken into the tag.

**Comment by gmao-jstassi** [comment]
Ricardo, all the files that you mention are in the unittests subdirectory. These files are not included in the build. Their only purpose is to test the Python scripts in the GSI_GridComp/etc directory, to verify that the scripts give expected output after being modified. That seems like a useful thing to have. The unittests/outdir subdirectory with its README file were previously in the repository but have been deleted with this PR.

**Comment by rtodling** [comment]
Why can't you design your test so that it runs off the RC files in the ETC directory of the installation? Why should you copy files from gsi/etc into your unit-test env. Sorry, but I still think there is a level of clean up to be done here. You haven't explained to me why you need files that identical to be in the repo w/ different names!

**Comment by gmao-jstassi** [comment]
Ricardo, my tests check for expected output from a given input, so if I used the rc files in the etc directory as my input, then I would have to update my tests every time somebody updates the rc files in the etc directory.

Some of my tests read an rc file and then write it back out, which for a successful test means that the output is going to be identical to the input. I think that is what you are seeing when two files with different names are identical.
________________________________
From: rtodling ***@***.***>
Sent: Monday, August 15, 2022 3:22 PM
To: GEOS-ESM/GEOSana_GridComp ***@***.***>
Cc: Stassi, Joe (GSFC-610.1)[SCIENCE SYSTEMS AND APPLICATIONS INC] ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [GEOS-ESM/GEOSana_GridComp] Feature/jstassi/#98 convert scripts to python3 (PR #99)


Why can't you design your test so that it runs off the RC files in the ETC directory of the installation? Why should you copy files from gsi/etc into your unit-test env. Sorry, but I still think there is a level of clean up to be done here. You haven't explained to me why you need files that identical to be in the repo w/ different names!

**Review by rtodling — APPROVED** [review]
Ok - I might still have my reservations about some of the things here, but since they: (i) don't affect anything in a run; (ii) are a move forward in terms of python - I think the best is to approve this and work on some cleanup later.

**Pull request merged**
