### PR TITLE
Save Error_input and Error_Adjust in nc_diag files.

### PR DESCRIPTION
**Pull request by gmao-jjin3**
Save Error_input and Error_Adjust in nc_diag files. These two variable are used as references in IODA files.

### CODE REVIEW

**Comment by gmao-msienkie** [comment]
What is the purpose of saving this in addition to the Errinv_Input and Errinv_Adjust (and taking the inverse of these in the IODA converter)?  Is there a problem with the precision of the data, so that the current GsiInputObsError and GsiAdjustObsError are not adequate?

**Comment by gmao-jjin3** [comment]
@gmao-msienkie  Yes, these new variables are kind of redundant.  "Errinv_Input" and "Errinv_Adjust" are not saved for all observations in current GSI. For example, it needs "luse(i)=TRUE" to save them in setupw.f90:
https://github.com/GEOS-ESM/GEOSana_GridComp/blob/develop/GEOSaana_GridComp/GSI_GridComp/setupw.f90#L1318

That's why some obserror are set to be huge values between line 791-795 in IODA converter:
https://github.com/JCSDA-internal/ioda-converters/blob/develop/src/gsi-ncdiag/gsi_ncdiag.py#L791

I didn't like those huge values in IODA, but I don't want to replace "Errinv_input" or "Errinv_Adjust" in order to avoid trouble to people who use these two variables.  That's how I came to these changes and updates in my IODA converter several weeks ago.

**Comment by gmao-jjin3** [comment]
@gmao-msienkie   I don't feel we really need these new "error_input" and "error_adjust", so I am going to close this PR. Thanks for your comment.

**Comment by gmao-jjin3** [comment]
Since we plan to use "GSI adjust observational error" for some observations in JEDI test, I re-open this PR.

**Review by rtodling — APPROVED** [review]
Works for me; corroborated zero-diff

**Pull request merged**
