### PR TITLE
Save SST for JEDI's tlap bias correction.

### PR DESCRIPTION
**Pull request by gmao-jjin3**
JEDI's bias correction procedure needs "average_surface_temperature_within_field_of_view" in obs GeoVaLs for TLapse bias correction.  This variable "tsavg5" was set missing in some GEOS diagnostic NC4 outputs in setuprad.f90. In this PR, this "tsavg5" is saved in all GSI's radiance data diagnostic NC4 files.

### CODE REVIEW

**Comment by gmao-jjin3** [comment]
@mathomp4  What is "dimagi/required-labels " which fails a check? Thanks.

**Comment by mathomp4** [comment]
> @mathomp4 What is "dimagi/required-labels " which fails a check? Thanks.

@gmao-jjin3 We require you to add a label, say "0-diff" or "non-0-diff", so that the PR approver knows if this would change the results or not.

**Comment by gmao-jjin3** [comment]
@mathomp4  Done. Thanks.

**Review by rtodling — APPROVED** [review]

**Comment by rtodling** [comment]
JJ: Your change is out of sync w/ the branch ... but I don't have a problem w/ the change.

**Comment by gmao-jjin3** [comment]
@rtodling Could you re-run x0044 for two cycles? I'd like to see whether we can make bias correction work in JEDI. Thank you very much!

**Comment by rtodling** [comment]
I am closing this since this is already in develop.

**Pull request closed without merging**
