### PR TITLE
Proposed R21C changes 2024-01-29

### PR DESCRIPTION
**Pull request by sdrabenh**
Labeled as zero-diff from the GCM perspective. Updates originally from @elakkraoui

### CODE REVIEW

**Comment by rtodling** [comment]
Can you provide a written list of all changes made here, please? Amal is probably the person to do this. Thanks

**Comment by elakkraoui** [comment]
> Can you provide a written list of all changes made here, please? Amal is probably the person to do this. Thanks

Here's a list of all the changes: 
[List_updates_4_M21C_CandidateTag.docx](https://github.com/GEOS-ESM/GEOSana_GridComp/files/14129620/List_updates_4_M21C_CandidateTag.docx)

Let me know if you questions about any of theses. Thanks.

**Review by rtodling — APPROVED** [review]
From what I can tell, these changes seem good.

I will take the word here that when ta2tb = false the code does give zero diff - as indicated in the label.

**Comment by rtodling** [comment]
Can you provide here the version number of GEOSana_GridComp this started from?

**Comment by elakkraoui** [comment]
> Can you provide here the version number of GEOSana_GridComp this started from?

I started from v1.5.5

GEOSana_GridComp       | (t) v1.5.5 (DH)           | (b) feature/aelakkra/r21c_DAScandidate

**Comment by rtodling** [comment]
Amal and Scott - it seems to me this is still in Draft mode - I can't finish this until the PR is officially submitted

**Comment by elakkraoui** [comment]
> Amal and Scott - it seems to me this is still in Draft mode - I can't finish this until the PR is officially submitted

You are right. They should've been submitted as official PRs. I'll check with Scott immediately.

**Comment by sdrabenh** [comment]
@rtodling @elakkraoui these PR were initially marked as drafts for reviewing. Clicking the button "Ready for review" now so they are regular PRs. Please keep in mind CircleCI may fail for some of these PRs as we don't have an automated way to checkout latest within the R21C branches just yet.

**Review by mathomp4 — APPROVED** [review]

**Pull request merged**
