### PR TITLE
Modify available channels file to completely turn off MetOp-A IASI 

### PR DESCRIPTION
**Pull request by gmao-msienkie**
Modified the available_channels.tbl file to set the end date for MetOp-A IASI as the same date where it was turned off in the active_channels.tbl file

### CODE REVIEW

**Comment by jing-guo** [comment]
I don't have any problem to merge it into develop branch. And the only thing I am not sure is if we would need this for the next release.

**Review by jing-guo — COMMENTED** [review]
I am still not sure what I am actually doing with all mouse clicking on GitHub webpages.  

As far as the change itself is concerned, I don't see any problem to merge these changes in.  However, it might be more helpful for later information tracking purposes to have
1. a reference to the source of information about the end-date, and
2. a statement to justify this change for the next release of the develop branch.

**Comment by gmao-msienkie** [comment]
Information about MetOp-A IASI termination can be found on the geos5.org radiance monitoring page
https://geos5.org/wiki/index.php?title=Talk:GEOS-5_ADAS_Radiance_Monitoring#MetOp-A_IASI_outage_-_Technology_Test.2C_end_of_MetOp-A_IASI_assimilation
The modification to 'available_channels.tbl' to completely turn off MetOp-A IASI was made per a request by Ricardo because the data during the last technology test generated too many error messages "READ_IASI WARNING uncertainty in lza" even when the data is read in as passive - thus the decision to move the end date earlier to avoid the messages.  The MetOp-A IASI instrument was finally switched off on October 15.

**Comment by jing-guo** [comment]
Yes, that is what we need.

However, I still don't see any where on this webpage to pull your change set into finish this PR.  Box "Merge pull request" is not clickable to me.  Maybe it requires a second "approving review"?

**Comment by gmao-msienkie** [comment]
maybe I've complicated things by putting the adas-gatekeepers in the 'review' request and I don't know how to undo that.  Sorry about that.  I know that Ricardo has been able to approve and merge my changes from this branch before.

**Review by jing-guo — APPROVED** [review]

**Pull request merged**
