### PR TITLE
Correct ssmi obserrors in e5304_m21c_jan98/run/gmao_global_satinfo.rc.

### PR DESCRIPTION
**Pull request by gmao-jjin3**
SSMI observational errors for clear-sky microwave radiance assimilation are in the M21C runs. We should use SSMI observational error for all-sky microwave radiance DA instead.   
Updates are made upon /home/dao_ops/e5304_m21c_jan98/run/gmao_global_satinfo.rc

### CODE REVIEW

**Comment by gmao-jjin3** [comment]
Here are correct values:

```
 ssmi_f10              1   -2   3.000  10.000   8.000  10.000   0.000      1       1      -1
 ssmi_f10              2   -2   6.000  20.000  15.000  10.000   0.000      1       1      -1
 ssmi_f10              3   -2   4.000  15.000  20.000  10.000   0.000      1       1      -1
 ssmi_f10              4   -2   5.000  20.000  30.000  10.000   0.000      1       1      -1
 ssmi_f10              5   -2   8.000  25.000  40.000  10.000   0.000      1       1      -1
 ssmi_f10              6   -2   5.000  15.000  15.000  10.000   0.000      1       1      -1
 ssmi_f10              7   -2  10.000  40.000  40.000  10.000   0.000      1       1      -1
 ssmi_f11              1   -2   3.000  10.000   8.000  10.000   0.000      1       1      -1
 ssmi_f11              2   -2   6.000  20.000  15.000  10.000   0.000      1       1      -1
 ssmi_f11              3   -2   4.000  15.000  20.000  10.000   0.000      1       1      -1
 ssmi_f11              4   -2   5.000  20.000  30.000  10.000   0.000      1       1      -1
 ssmi_f11              5   -2   8.000  25.000  40.000  10.000   0.000      1       1      -1
 ssmi_f11              6   -2   5.000  15.000  15.000  10.000   0.000      1       1      -1
 ssmi_f11              7   -2  10.000  40.000  40.000  10.000   0.000      1       1      -1
 ssmi_f13              1   -2   3.000  10.000   8.000  10.000   0.000      1       1      -1
 ssmi_f13              2   -2   6.000  20.000  15.000  10.000   0.000      1       1      -1
 ssmi_f13              3   -2   4.000  15.000  20.000  10.000   0.000      1       1      -1
 ssmi_f13              4   -2   5.000  20.000  30.000  10.000   0.000      1       1      -1
 ssmi_f13              5   -2   8.000  25.000  40.000  10.000   0.000      1       1      -1
 ssmi_f13              6   -2   5.000  15.000  15.000  10.000   0.000      1       1      -1
 ssmi_f13              7   -2  10.000  40.000  40.000  10.000   0.000      1       1      -1
 ssmi_f14              1   -2   3.000  10.000   8.000  10.000   0.000      1       1      -1
 ssmi_f14              2   -2   6.000  20.000  15.000  10.000   0.000      1       1      -1
 ssmi_f14              3   -2   4.000  15.000  20.000  10.000   0.000      1       1      -1
 ssmi_f14              4   -2   5.000  20.000  30.000  10.000   0.000      1       1      -1
 ssmi_f14              5   -2   8.000  25.000  40.000  10.000   0.000      1       1      -1
 ssmi_f14              6   -2   5.000  15.000  15.000  10.000   0.000      1       1      -1
 ssmi_f14              7   -2  10.000  40.000  40.000  10.000   0.000      1       1      -1
 ssmi_f15              1   -2   3.000  10.000   8.000  10.000   0.000      1       1      -1
 ssmi_f15              2   -2   6.000  20.000  15.000  10.000   0.000      1       1      -1
 ssmi_f15              3   -2   4.000  15.000  20.000  10.000   0.000      1       1      -1
 ssmi_f15              4   -2   5.000  20.000  30.000  10.000   0.000      1       1      -1
 ssmi_f15              5   -2   8.000  25.000  40.000  10.000   0.000      1       1      -1
 ssmi_f15              6   -2   5.000  15.000  15.000  10.000   0.000      1       1      -1
 ssmi_f15              7   -2  10.000  40.000  40.000  10.000   0.000      1       1      -1

```

**Comment by rtodling** [comment]
You can correct this to develop - but I believe this needs to really go into the R21C branch. Can you redirect your fix there. I can bring the fix to develop in another PR.

**Comment by rtodling** [comment]
This is now in the following branch:

feature/rtodling/merge_5295p7_x50R1_2_dev

which is aimed at develop and 5.40.x

Again, pls redirect this PR to the R21C branch (as opposed to develop).

**Comment by gmao-jjin3** [comment]
Thanks. Let me see whether Amal already corrected it. I close this PR.

**Pull request closed without merging**
