### PR TITLE
Feature/wgu/crtm2.4.0+i rbugfix

### PR DESCRIPTION
**Pull request by gmao-wgu**
This PR was created to introduce the minor bug fixes to IR from the NCEP including the updated surface temperature check in qcmod.f90 and some tweaks to the selection of clear scenes during thinning for AIRS, IASI and CrIS-FSR.  For  CriS-FSR, the bufr reading was also updated to be consistent with CRTM 2.4.0.  crtm_interface.f90 was updated to handle the allsky assimilation of AMSR2,MHS and GMI under CRTM 2..4.0. gamo_global_satinfo.rc was also updated to go with the reconfigured cloud detection for CrIS-FSR and the reconfigured gross-check for IR.

### CODE REVIEW

**Review by rtodling — COMMENTED** [review]
If this code is final and aimed at develop, I need to ask  for the comments in cram_interface  "yzhu_test" be removed please.

**Review by rtodling — COMMENTED** [review]
Another issue is the obs error covariance wired to Wei's location. This needs to be unwired. 

Is the R cov changing because there are new channels being used for IR?

**Review by rtodling — COMMENTED** [review]
Why are you changing the iuse flags in the satinfo file? This changes more than just the IR? Is this because you want all channels to be monitored? Did you make sure this change is zero diff as you expect?

**Comment by gmao-wgu** [comment]
> Why are you changing the iuse flags in the satinfo file? This changes more than just the IR? Is this because you want all channels to be monitored? Did you make sure this change is zero diff as you expect?

As far as I knew, all the changes should be in IR to reflect the reconfigured cloud detection for CrIS-Fsr and the reconfigured gross-check for IR. I will take a look when I get to home tonight.

**Comment by gmao-wgu** [comment]
> Another issue is the obs error covariance wired to Wei's location. This needs to be unwired.
> 
> Is the R cov changing because there are new channels being used for IR?

I am sorry I did not get it.  The only thing I could think of that was pointing to my directory is the CRTM data files in analyzer.

**Comment by gmao-wgu** [comment]
@rtodling I checked the files changed(totally 9 files), I could not see the issues you mentioned except the one: comments like "yzhu" should be removed in the code.

**Review by rtodling — APPROVED** [review]
All good by me.
I unwired the CRTM path from being under Wei's directory to the shared directory
I also added a zero-diff change to GSI_GridComp to allow for more general grid settings (prep for JEDI).

**Pull request merged**
